allow to filter entries by title per subscription
maubot/rss pull request #57
Opened 2024-07-04 15:51 UTC by sebhoss

fixes #6

2024-08-18 04:30 UTC, sebhoss commented
@tulir sorry missed that there were lint errors - I hope that those are fixed now..

2024-08-18 12:32 UTC, sebhoss commented
Ok sorry again @tulir - third time's a charm? This time I installed all the tools and basically run the entire lint pipeline locally:

- `isort ./rss`
- `black ./rss`
- `pre-commit run -av trailing-whitespace`
- `pre-commit run -av end-of-file-fixer`
- `pre-commit run -av check-yaml`
- `pre-commit run -av check-added-large-files`

All checks are passing locally - sorry again for the inconvenience..

2024-08-30 18:21 UTC, tulir requested changes

2024-08-30 18:21 UTC, tulir commented on rss/bot.py
> +            self.log.debug(f"Feed '{feed.id}' ({feed.title}) has no exclude filter")
These logs should be `.trace()` instead of debug or removed entirely

2024-08-30 18:21 UTC, tulir commented on rss/bot.py
> +    async def set_filter(self, evt: MessageEvent, feed_id: int, title_exclude_filter: str) -> None:
This should validate the filter before saving it (probably just `re.compile`)

2024-08-30 18:21 UTC, tulir commented on rss/migrations.py
> +@upgrade_table.register(description="Latest revision", upgrades_to=4)
You forgot to update the `CREATE TABLE` statement with the new column

2025-01-06 06:09 UTC, sebhoss commented on rss/bot.py
> +            self.log.debug(f"Feed '{feed.id}' ({feed.title}) has no exclude filter")
ok removed

2025-01-06 06:09 UTC, sebhoss commented on rss/bot.py
> +    async def set_filter(self, evt: MessageEvent, feed_id: int, title_exclude_filter: str) -> None:
added a `re.compile` step

2025-01-06 06:09 UTC, sebhoss commented on rss/migrations.py
> +@upgrade_table.register(description="Latest revision", upgrades_to=4)
added the missing column

2025-01-06 06:12 UTC, sebhoss commented
squashed all commits into one

2025-02-09 13:54 UTC, sebhoss commented
rebased on latest master - @tulir can you take another look?

2026-07-05 20:14 UTC, closed without merging